from kloak.data import Schema, SchemaEntry, SchemaList
from kloak.data.knex_pydantic_schema import KnexPydanticSchema
from pydantic import BaseModel, Field


class ResearchReport(KnexPydanticSchema):
    """Schema for research reports generated by research director agent."""

    vendor_name: str = Field(..., description="Name of the vendor.")
    research_report: str = Field(..., description="Research report.")
    citations: list[str] = Field(
        default_factory=list,
        description="List of citations (Chicago-style) used in the report.",
    )


class ResearchQuery(KnexPydanticSchema):
    """
    Schema for research queries generated by research director agent.

    Parameters
    ----------
        vendor_name (str): Name of the vendor.
        finance (str): Finance query.
        political (str): Political query.
        compliance (str): Compliance query.
        foci (str): Foreign ownership, control, and/or influence query.
        cybersecurity (str): Cybersecurity query.
        manufacturing (str): Manufacturing query.
        logistics (str): Logistics query.
        quality (str): Quality query.
        reasoning (str): Reasoning behind the research queries.

    """

    vendor_name: str = Field(..., description="Name of the vendor.")
    finance: str = Field(..., description="Finance query.")
    political: str = Field(..., description="Political query.")
    compliance: str = Field(..., description="Compliance query.")
    foci: str = Field(
        ..., description="foreign ownership, control, and/or influence query."
    )
    cybersecurity: str = Field(..., description="Cybersecurity query.")
    manufacturing: str = Field(..., description="Manufacturing query.")
    logistics: str = Field(..., description="Logistics query.")
    quality: str = Field(..., description="Quality query.")
    reasoning: str = Field(..., description="Reasoning behind the research queries.")


class SynthesizedReport(KnexPydanticSchema):
    """Schema for synthesized reports generated by the synthesis agent."""

    report: str = Field(..., description="Synthesized report.")
    risk_score: float = Field(
        ..., description="Risk score (1 to 10, low risk to high risk)"
    )
    course_of_action: str = Field(..., description="Recommended course of action.")
    citations: list[str] = Field(
        default_factory=list, description="List of citations (Chicago-style)."
    )


# Vendor Discovery Schemas
class VendorDetail(KnexPydanticSchema):
    """Represents the structured details of a single potential vendor."""
    name: str = Field(..., description="The name of the potential vendor.")
    primary_offering: str = Field(...,
        description="The main material or service this vendor supplies relevant to the query.")
    location_or_service_area: str = Field(...,
        description="The primary location or geographic service area of the vendor, indicating their ability to supply to the target location.")
    website_url: str | None = Field(None, description="The main website URL for the vendor, if found.")
    summary: str = Field(...,
        description="A brief summary explaining why this vendor is a good match based on the initial search.")

VendorDetailSchema = Schema(
    required = [
        SchemaEntry(name="name", attr_type=str, description="The name of the potential vendor"),
        SchemaEntry(name="service_area", attr_type=str,
                    description="The primary location or geographic service area of the vendor, indicating ability to supply to target location"),
        SchemaEntry(name="summary", attr_type=str,
                    description="A brief summary explaining why this vendor is a good match based on the initial search")
    ],
    optional= [
        SchemaEntry(name="website", attr_type=str,
                    description="The main website URL for the vendor, if found")
    ]
)


MaterialSchema = Schema(
    required = [
        SchemaEntry(name="material", attr_type=str,
                    description="The specific material the user asked to find"),
        SchemaEntry(name="target_location", attr_type=str,
                    description="The location where the material needs to be supplied"),
    ]
)

VendorOnlyListSchema = Schema(
    required = [
        SchemaEntry(name="vendors", attr_type=SchemaList(sub_type=str),
                    description="A curated list of potential vendors"),
    ]
)

VendorShortListSchema = Schema(
    required= [
        SchemaEntry(name="material", attr_type=str,
                    description="The specific material the user asked to find"),
        SchemaEntry(name="target_location", attr_type=str,
                    description="The location where the material needs to be supplied"),
        SchemaEntry(name="vendors", attr_type=SchemaList(sub_type=str),
                    description="A curated list of potential vendors"),
        SchemaEntry(name="discovery_summary", attr_type=str,
                    description="A brief summary of the discovery ")
    ]
)

class VendorShortlist(KnexPydanticSchema):
    """Represents the final, curated shortlist of potential vendors."""
    material_requested: str = Field(..., description="The specific material the user asked to find.")
    target_location: str = Field(..., description="The location where the material needs to be supplied.")
    vendors: list[VendorDetail] = Field(..., description="A curated list of up to 10 potential vendors.")
    discovery_summary: str = Field(..., description="A brief summary of the discovery process and key considerations.")
