from kloak.data.knex_pydantic_schema import KnexPydanticSchema
from pydantic import Field


class ResearchReport(KnexPydanticSchema):
    """Schema for research reports generated by research director agent."""

    vendor_name: str = Field(..., description="Name of the vendor.")
    research_report: str = Field(..., description="Research report.")
    citations: list[str] = Field(
        default_factory=list,
        description="List of citations (Chicago-style) used in the report.",
    )


class ResearchQuery(KnexPydanticSchema):
    """Schema for research queries generated by research director agent."""

    vendor_name: str = Field(..., description="Name of the vendor.")
    finance: str = Field(..., description="Finance query.")
    political: str = Field(..., description="Political query.")
    capability: str = Field(..., description="Capability query.")
    security: str = Field(..., description="Security query.")
    reasoning: str = Field(..., description="Reasoning behind the research queries.")


class SynthesizedReport(KnexPydanticSchema):
    """Schema for synthesized reports generated by the synthesis agent."""

    report: str = Field(..., description="Synthesized report.")
    citations: list[str] = Field(
        default_factory=list, description="List of citations (Chicago-style)."
    )
