from kloak.data.knex_pydantic_schema import KnexPydanticSchema
from pydantic import Field


class ResearchReport(KnexPydanticSchema):
    """Schema for research reports generated by research director agent."""

    vendor_name: str = Field(..., description="Name of the vendor.")
    research_report: str = Field(..., description="Research report.")
    citations: list[str] = Field(
        default_factory=list,
        description="List of citations (Chicago-style) used in the report.",
    )


class ResearchQuery(KnexPydanticSchema):
    """
    Schema for research queries generated by research director agent.

    Parameters
    ----------
        vendor_name (str): Name of the vendor.
        finance (str): Finance query.
        political (str): Political query.
        compliance (str): Compliance query.
        foci (str): Foreign ownership, control, and/or influence query.
        cybersecurity (str): Cybersecurity query.
        manufacturing (str): Manufacturing query.
        logistics (str): Logistics query.
        quality (str): Quality query.
        reasoning (str): Reasoning behind the research queries.

    """

    vendor_name: str = Field(..., description="Name of the vendor.")
    finance: str = Field(..., description="Finance query.")
    political: str = Field(..., description="Political query.")
    compliance: str = Field(..., description="Compliance query.")
    foci: str = Field(
        ..., description="foreign ownership, control, and/or influence query."
    )
    cybersecurity: str = Field(..., description="Cybersecurity query.")
    manufacturing: str = Field(..., description="Manufacturing query.")
    logistics: str = Field(..., description="Logistics query.")
    quality: str = Field(..., description="Quality query.")
    reasoning: str = Field(..., description="Reasoning behind the research queries.")


class SynthesizedReport(KnexPydanticSchema):
    """Schema for synthesized reports generated by the synthesis agent."""

    report: str = Field(..., description="Synthesized report.")
    risk_score: float = Field(
        ..., description="Risk score (1 to 10, low risk to high risk)"
    )
    course_of_action: str = Field(..., description="Recommended course of action.")
    citations: list[str] = Field(
        default_factory=list, description="List of citations (Chicago-style)."
    )
